//
//  CSS Colors.swift
//  HEALPix Viewer
//
//  Created by Andrei Frolov on 2023-07-20.
//

import SwiftUI

// SwiftUI named colors
let system_colors: [String: Color] = [
    // named colors
    "Black":                .black,
    "Blue":                 .blue,
    "Brown":                .brown,
    "Clear":                .clear,
    "Cyan":                 .cyan,
    "Gray":                 .gray,
    "Grey":                 .gray,
    "Green":                .green,
    "Indigo":               .indigo,
    "Mint":                 .mint,
    "Orange":               .orange,
    "Pink":                 .pink,
    "Purple":               .purple,
    "Red":                  .red,
    "Teal":                 .teal,
    "White":                .white,
    "Yellow":               .yellow,
    
    // semantic colors
    "Accent":               .accentColor,
    "Primary":              .primary,
    "Secondary":            .secondary,
    "Disabled":             .disabled
]

// conflicts resolved in favour of Apple system colors, then crayons, then CSS
let css_colors: [String: Int] = [
    // Apple crayon colors (in sRGB)
    "Licorice":             0x000000FF,
    "Lead":                 0x212121FF,
    "Tungsten":             0x424242FF,
    "Iron":                 0x5E5E5EFF,
    "Steel":                0x797979FF,
    "Tin":                  0x919191FF,
    "Nickel":               0x929292FF,
    "Aluminum":             0xA9A9A9FF,
    "Magnesium":            0xC0C0C0FF,
    "Silver":               0xD5D5D5FF,
    "Mercury":              0xEAEAEAFF,
    "Snow":                 0xFEFFFFFF,
    "Cayenne":              0x941100FF,
    "Mocha":                0x935100FF,
    "Asparagus":            0x929000FF,
    "Fern":                 0x4E8F00FF,
    "Clover":               0x008E00FF,
    "Moss":                 0x008F51FF,
//  "Teal":                 0x009192FF,
    "Ocean":                0x005392FF,
    "Midnight":             0x011892FF,
    "Eggplant":             0x521B92FF,
    "Plum":                 0x942092FF,
    "Maroon":               0x941651FF,
    "Marascino":            0xFF2600FF,
    "Tangerine":            0xFF9300FF,
    "Lemon":                0xFEFB00FF,
    "Lime":                 0x8DF900FF,
    "Spring":               0x00F900FF,
    "SeaFoam":              0x00FA92FF,
    "Turquoise":            0x00FCFFFF,
    "Aqua":                 0x0096FFFF,
    "Blueberry":            0x0432FFFF,
    "Grape":                0x9437FFFF,
    "Magenta":              0xFF40FFFF,
    "Strawberry":           0xFF2F92FF,
    "Salmon":               0xFF7D78FF,
    "Cantaloupe":           0xFFD478FF,
    "Banana":               0xFEFC78FF,
    "Honeydew":             0xD4FB78FF,
    "Flora":                0x72FA78FF,
    "Spindrift":            0x72FCD5FF,
    "Ice":                  0x73FDFFFF,
    "Sky":                  0x75D5FFFF,
    "Orchid":               0x7980FFFF,
    "Lavender":             0xD783FFFF,
    "Bubblegum":            0xFF84FFFF,
    "Carnation":            0xFF89D8FF,
    
    // CSS named colors [https://css-tricks.com/snippets/css/named-colors-and-hex-equivalents/]
    "Alice Blue":           0xF0F8FFFF,
    "Antique White":        0xFAEBD7FF,
//  "Aqua":                 0x00FFFFFF,
    "Aquamarine":           0x7FFFD4FF,
    "Azure":                0xF0FFFFFF,
    "Beige":                0xF5F5DCFF,
    "Bisque":               0xFFE4C4FF,
//  "Black":                0x000000FF,
    "Blanched Almond":      0xFFEBCDFF,
//  "Blue":                 0x0000FFFF,
    "Blue Violet":          0x8A2BE2FF,
//  "Brown":                0xA52A2AFF,
    "Burly Wood":           0xDEB887FF,
    "Cadet Blue":           0x5F9EA0FF,
    "Chartreuse":           0x7FFF00FF,
    "Chocolate":            0xD2691EFF,
    "Coral":                0xFF7F50FF,
    "Cornflower Blue":      0x6495EDFF,
    "Cornsilk":             0xFFF8DCFF,
    "Crimson":              0xDC143CFF,
//  "Cyan":                 0x00FFFFFF,
    "Dark Blue":            0x00008BFF,
    "Dark Cyan":            0x008B8BFF,
    "Dark Goldenrod":       0xB8860BFF,
    "Dark Gray":            0xA9A9A9FF,
    "Dark Grey":            0xA9A9A9FF,
    "Dark Green":           0x006400FF,
    "Dark Khaki":           0xBDB76BFF,
    "Dark Magenta":         0x8B008BFF,
    "Dark Olive Green":     0x556B2FFF,
    "Dark Orange":          0xFF8C00FF,
    "Dark Orchid":          0x9932CCFF,
    "Dark Red":             0x8B0000FF,
    "Dark Salmon":          0xE9967AFF,
    "Dark Sea Green":       0x8FBC8FFF,
    "Dark Slate Blue":      0x483D8BFF,
    "Dark Slate Gray":      0x2F4F4FFF,
    "Dark Slate Grey":      0x2F4F4FFF,
    "Dark Turquoise":       0x00CED1FF,
    "Dark Violet":          0x9400D3FF,
    "Deep Pink":            0xFF1493FF,
    "Deep Sky Blue":        0x00BFFFFF,
    "Dim Gray":             0x696969FF,
    "Dim Grey":             0x696969FF,
    "Dodger Blue":          0x1E90FFFF,
    "Fire Brick":           0xB22222FF,
    "Floral White":         0xFFFAF0FF,
    "Forest Green":         0x228B22FF,
    "Fuchsia":              0xFF00FFFF,
    "Gainsboro":            0xDCDCDCFF,
    "Ghost White":          0xF8F8FFFF,
    "Gold":                 0xFFD700FF,
    "Goldenrod":            0xDAA520FF,
//  "Gray":                 0x808080FF,
//  "Grey":                 0x808080FF,
//  "Green":                0x008000FF,
    "Green Yellow":         0xADFF2FFF,
//  "HoneyDew":             0xF0FFF0FF,
    "Hot Pink":             0xFF69B4FF,
    "Indian Red":           0xCD5C5CFF,
//  "Indigo":               0x4B0082FF,
    "Ivory":                0xFFFFF0FF,
    "Khaki":                0xF0E68CFF,
//  "Lavender":             0xE6E6FAFF,
    "Lavender Blush":       0xFFF0F5FF,
    "Lawn Green":           0x7CFC00FF,
    "Lemon Chiffon":        0xFFFACDFF,
    "Light Blue":           0xADD8E6FF,
    "Light Coral":          0xF08080FF,
    "Light Cyan":           0xE0FFFFFF,
    "Light Goldenrod":      0xFAFAD2FF,
    "Light Gray":           0xD3D3D3FF,
    "Light Grey":           0xD3D3D3FF,
    "Light Green":          0x90EE90FF,
    "Light Pink":           0xFFB6C1FF,
    "Light Salmon":         0xFFA07AFF,
    "Light Sea Green":      0x20B2AAFF,
    "Light Sky Blue":       0x87CEFAFF,
    "Light Slate Gray":     0x778899FF,
    "Light Slate Grey":     0x778899FF,
    "Light Steel Blue":     0xB0C4DEFF,
    "Light Yellow":         0xFFFFE0FF,
//  "Lime":                 0x00FF00FF,
    "Lime Green":           0x32CD32FF,
    "Linen":                0xFAF0E6FF,
//  "Magenta":              0xFF00FFFF,
//  "Maroon":               0x800000FF,
    "Medium Aquamarine":    0x66CDAAFF,
    "Medium Blue":          0x0000CDFF,
    "Medium Orchid":        0xBA55D3FF,
    "Medium Purple":        0x9370D8FF,
    "Medium Sea Green":     0x3CB371FF,
    "Medium Slate Blue":    0x7B68EEFF,
    "Medium Spring Green":  0x00FA9AFF,
    "Medium Turquoise":     0x48D1CCFF,
    "Medium Violet Red":    0xC71585FF,
    "Midnight Blue":        0x191970FF,
    "Mint Cream":           0xF5FFFAFF,
    "Misty Rose":           0xFFE4E1FF,
    "Moccasin":             0xFFE4B5FF,
    "Navajo White":         0xFFDEADFF,
    "Navy":                 0x000080FF,
    "Old Lace":             0xFDF5E6FF,
    "Olive":                0x808000FF,
    "Olive Drab":           0x6B8E23FF,
//  "Orange":               0xFFA500FF,
    "Orange Red":           0xFF4500FF,
//  "Orchid":               0xDA70D6FF,
    "Pale Goldenrod":       0xEEE8AAFF,
    "Pale Green":           0x98FB98FF,
    "Pale Turquoise":       0xAFEEEEFF,
    "Pale Violet Red":      0xD87093FF,
    "Papaya Whip":          0xFFEFD5FF,
    "Peach Puff":           0xFFDAB9FF,
    "Peru":                 0xCD853FFF,
//  "Pink":                 0xFFC0CBFF,
//  "Plum":                 0xDDA0DDFF,
    "Powder Blue":          0xB0E0E6FF,
//  "Purple":               0x800080FF,
//  "Red":                  0xFF0000FF,
    "Rosy Brown":           0xBC8F8FFF,
    "Royal Blue":           0x4169E1FF,
    "Saddle Brown":         0x8B4513FF,
//  "Salmon":               0xFA8072FF,
    "Sandy Brown":          0xF4A460FF,
    "Sea Green":            0x2E8B57FF,
    "Sea Shell":            0xFFF5EEFF,
    "Sienna":               0xA0522DFF,
//  "Silver":               0xC0C0C0FF,
    "Sky Blue":             0x87CEEBFF,
    "Slate Blue":           0x6A5ACDFF,
    "Slate Gray":           0x708090FF,
    "Slate Grey":           0x708090FF,
//  "Snow":                 0xFFFAFAFF,
    "Spring Green":         0x00FF7FFF,
    "Steel Blue":           0x4682B4FF,
    "Tan":                  0xD2B48CFF,
//  "Teal":                 0x008080FF,
    "Thistle":              0xD8BFD8FF,
    "Tomato":               0xFF6347FF,
//  "Turquoise":            0x40E0D0FF,
    "Violet":               0xEE82EEFF,
    "Wheat":                0xF5DEB3FF,
//  "White":                0xFFFFFFFF,
    "White Smoke":          0xF5F5F5FF,
//  "Yellow":               0xFFFF00FF,
    "Yellow Green":         0x9ACD32FF
]

// all known color names
let named_colors = { (Array(system_colors.keys) + Array(css_colors.keys)).sorted() }()

// named color LUT
let named_color_lut: [String: Color] = {
    let system = Dictionary(uniqueKeysWithValues: system_colors.map { ($0.lowercased().filter{!$0.isWhitespace}, $1) })
    let css = Dictionary(uniqueKeysWithValues: css_colors.map { ($0.lowercased().filter{!$0.isWhitespace}, Color(hex: $1)) })
    return system.merging(css, uniquingKeysWith: { (first, _) in first })
}()

// system color name LUT
let system_color_lut = { Dictionary(system_colors.map { ($1,$0) }, uniquingKeysWith: { (a, b) in min(a,b) }) }()

// sRGB hex value name LUT
let hex_color_lut = { Dictionary(css_colors.map { ($1,$0) }, uniquingKeysWith: { (a, b) in min(a,b) }) }()
